//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryHistory
    {
        public int id { get; set; }
        public int materialId { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
