//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CostChangeHistory = new HashSet<CostChangeHistory>();
            this.MaterialInProduct = new HashSet<MaterialInProduct>();
            this.ProductInOrder = new HashSet<ProductInOrder>();
        }
    
        public int id { get; set; }
        public string article { get; set; }
        public int productTypeId { get; set; }
        public string name { get; set; }
        public string decription { get; set; }
        public byte[] image { get; set; }
        public decimal partneerMinCost { get; set; }
        public decimal lenght { get; set; }
        public decimal width { get; set; }
        public decimal height { get; set; }
        public decimal net { get; set; }
        public decimal gross { get; set; }
        public byte[] qualitySertificat { get; set; }
        public string GOST { get; set; }
        public System.TimeSpan productionTime { get; set; }
        public decimal selfcosting { get; set; }
        public int workshopNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostChangeHistory> CostChangeHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialInProduct> MaterialInProduct { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInOrder> ProductInOrder { get; set; }
    }
}
